--- 
- 
  become: true
  hosts: "172.31.1.190"
  tasks: 
    - 
      name: "Install apache"
      yum: 
        name: httpd
        state: present
    - 
      name: "Install Git"
      yum: 
        name: git
        state: present
    - 
      git: 
        dest: /var/www/html
        name: "Install static website from Git"
        repo: "https://github.com/javahometech/javahome-app"